default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: kiita_development

test:
  <<: *default
  database: kiita_test

production:
  <<: *default
  database: kiita_production
